//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NetWebApiMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int ExamID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<int> MaxScore { get; set; }
    }
}
